///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FetchJson {
/*
{
  "id": "0",
  "available": "true",
  "rent": 1000,
  "apartment": "Clementina DuBuque",
  "size": "1800",
  "owner": "Mohnish",
  "address": "Ayodhya Bypass",
  "city": "Bhopal",
  "picture": "https://source.unsplash.com/480x480/?home",
  "likes": "0"
} 
*/

  String? id;
  String? available;
  String? rent;
  String? apartment;
  String? size;
  String? owner;
  String? address;
  String? city;
  String? picture;
  String? likes;
  String? phone;

  FetchJson(
    List jsonList, {
    this.id,
    this.available,
    this.rent,
    this.apartment,
    this.size,
    this.owner,
    this.address,
    this.city,
    this.picture,
    this.likes,
    this.phone,
  });
  FetchJson.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    available = json['available']?.toString();
    rent = json['rent']?.toString();
    apartment = json['apartment']?.toString();
    size = json['size']?.toString();
    owner = json['owner']?.toString();
    address = json['address']?.toString();
    city = json['city']?.toString();
    picture = json['picture']?.toString();
    likes = json['likes']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['available'] = available;
    data['rent'] = rent;
    data['apartment'] = apartment;
    data['size'] = size;
    data['owner'] = owner;
    data['address'] = address;
    data['city'] = city;
    data['picture'] = picture;
    data['likes'] = likes;
    data['phone'] = phone;
    return data;
  }
}
